[workspace]
resolver = "3"
members = [
    "crates/nostr_automerge",
    "tools/nostr_automerge_conformance",
    "tools/nostr_automerge_xtask",
]

[workspace.package]
version = "0.1.0-alpha.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Tyson Lupul <tyson@radroots.org>"]
readme = "README.md"
repository = "https://github.com/triesap/nostr_automerge"
rust-version = "1.92.0"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unreachable_pub = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unwrap_used = "deny"

[workspace.dependencies]
automerge = { version = "=0.10.0", default-features = false }
base64 = { version = "=0.22.1" }
nostr_automerge = { path = "crates/nostr_automerge", version = "=0.1.0-alpha.0" }
serde = { version = "=1.0.219" }
serde_json = { version = "=1.0.142" }
secp256k1 = { version = "=0.31.1", default-features = false, features = ["std"] }
sha2 = { version = "=0.10.9" }
url = { version = "=2.5.4" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.wasm-release]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
